### PR TITLE
parser fixes

### LINKED ISSUE #131: Fix "remove this message" in data
"Remove this message" isn't being removed from geojson data.

### LINKED ISSUE #143: Fix date format bug in parser algorithm
If the date format in the exported file is 12/10/24 instead of 12/10/2024 (note the year format), the parser shows an error and the chat is not converted into a map.

### PR DESCRIPTION
**Pull request by acholyn**
closes #143 - allows matching of 2 or 4 digits in first and third place of date
if year is 2 digits set it to 4

closes #131

### CODE REVIEW

File: src/import_whatsapp.js [hunk 1]
```diff
@@ -252,13 +258,13 @@ const setImgMsgRegex = (fileType) => {
 		// console.info("ios format");
 		// iOS format
 		messageRegex =
-			/\[(\d{2}\/\d{2}\/\d{4}),\s(\d{1,2}:\d{2}:\d{2}\s(?:AM|PM))\]\s(.*?):\s(.+?)(?=\n\[|$)/gs;
+			/\[(\d{2,4}\/\d{2}\/\d{2,4}),\s(\d{1,2}:\d{2}:\d{2}\s(?:AM|PM))\]\s(.*?):\s(.+?)(?=\n\[|$)/gs;
```
Comment (tcouch) [inline src/import_whatsapp.js:261]: You deleted the date from the look ahead at the end.
```suggestion
			/\[(\d{2}\/\d{2}\/\d{2,4}),\s(\d{1,2}:\d{2}:\d{2}\s(?:AM|PM))\]\s(.*?):\s(.+?)(?=(\n\d{2}\/\d{2}\/\d{2,4})|$)/gs;
```

File: src/import_whatsapp.js [hunk 2]
```diff
@@ -252,13 +258,13 @@ const setImgMsgRegex = (fileType) => {
...
 		imgFileRegex = /<attached: (\d+-[\w\-_]+\.(jpg|jpeg|png|gif))>/gim;
 	} else if (fileType.match(/\d{2}\//)) {
 		// console.info("android format");
 		// Android format
 		messageRegex =
-			/(\d{2}\/\d{2}\/\d{4}),?\s(\d{1,2}:\d{2})(?:\s?(?:AM|PM|am|pm))?\s-\s(.*?):[\t\f\cK ]((.|\n)*?)(?=(\n\d{2}\/\d{2}\/\d{4})|$)/g;
+			/(\d{2,4}\/\d{2}\/\d{2,4}),?\s(\d{1,2}:\d{2})(?:\s?(?:AM|PM|am|pm))?\s-\s(.*?):[\t\f\cK ]((.|\n)*?)(?=(\n\d{2}\/\d{2}\/\d{4})|$)/g;
```
Comment (tcouch) [inline src/import_whatsapp.js:267]: The day part doesn't need to be able to accept 4 chars, and you need to edit the lookahead to allow YY as well.
```suggestion
			/(\d{2}\/\d{2}\/\d{2,4}),?\s(\d{1,2}:\d{2})(?:\s?(?:AM|PM|am|pm))?\s-\s(.*?):[\t\f\cK ]((.|\n)*?)(?=(\n\d{2}\/\d{2}\/\d{2,4})|$)/g;
```

File: src/import_whatsapp.js (hunk 1 above)
Comment (tcouch) [reply src/import_whatsapp.js:261]: Did you test this?

**Review by tcouch — CHANGES_REQUESTED** [review]

File: src/import_whatsapp.js [hunk 3]
```diff
@@ -197,6 +201,8 @@ const cleanMsgContent = (content, location, imgFileRegex) => {
 				)
 		)
 		.join("\n");
+	content = content.replace(/remove_this_msg\n/g, "");
+	content = content.replace(/\n\n\n/g, "\n");
```
[the remark this answers is not in the document]
Comment (acholyn) [reply src/import_whatsapp.js:205]: I think we only get 3 (or 4) due to the cleaning, but we do use 1 and 2 for spacing, so I just figured if we remove lumps of 3 that stops loads of unnecessary whitespace but if it's functional then that's still preserved

File: src/import_whatsapp.js [hunk 4]
```diff
@@ -144,6 +144,10 @@ const formatDateString = (date, time) => {
 		}
 	} else [hour, min, sec = "00"] = time.split(":"); // 24hr format used already
 
+	if (year.length === 2) {
+		year = "20" + year;
```
[the remark this answers is not in the document]
Comment (acholyn) [reply src/import_whatsapp.js:148]: 🤞

File: src/import_whatsapp.js (hunk 1 above)
Comment (acholyn) [reply src/import_whatsapp.js:261]: I did and didn't notice a difference between what's on prod and my local but will put it back anyway to be safe

File: src/import_whatsapp.js (hunk 2 above)
Comment (acholyn) [reply src/import_whatsapp.js]: can't it sometimes come in yyyy/mm/dd as well though? I thought year isn't always last, or was that just because of the format we create?

Comment (tcouch) [reply src/import_whatsapp.js]: If that's the case then formatDateString needs to be updated to figure out if day/year comes first. At the moment it assumes day (line 133)

**Review by tcouch — APPROVED** [review]
